# Generated by Django 3.1.4 on 2021-02-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=30, null=True)),
                ('github', models.CharField(blank=True, max_length=60, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=60, null=True)),
                ('personal_website', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailIPLocator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('whatsapp_message', models.CharField(max_length=1000, null=True)),
                ('facebook_link', models.CharField(max_length=100, null=True)),
                ('feedback_upvote', models.IntegerField(default=0)),
                ('feedback_loved', models.IntegerField(default=0)),
                ('feedback_amazed', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(blank=True, to='blog_app.BlogPostComment')),
                ('tags', models.ManyToManyField(to='blog_app.Tag')),
                ('team', models.ManyToManyField(to='blog_app.Author')),
            ],
        ),
    ]
